### ISSUE TITLE
Tried to run the script, but get error

### ISSUE THREAD

**Issue by metasikander** [mxbi/tailscale-hostmap#4]
when i run the script it i get an error:
```bash
~]$ sudo /usr/bin/python /usr/bin/tailscale-hostmap.py
Traceback (most recent call last):
  File "/usr/bin/tailscale-hostmap.py", line 210, in <module>
    sys.exit(main())
  File "/usr/bin/tailscale-hostmap.py", line 198, in main
    hosts_lines = update_hosts(format_hosts_lines(tailscale_peers()))
  File "/usr/bin/tailscale-hostmap.py", line 110, in format_hosts_lines
    if len(valid_peers(peers)):
TypeError: object of type 'generator' has no len()
```
do you have an idea why this might be happening?

OS: Fedora 36
Pyton: Python 3.10.7

**Comment by drjgouveia** [comment]
Hi!
I had the same error and changing this:
```
def valid_peers(
    peers: typing.List[PeerInfo],
) -> typing.Generator[typing.Union[PeerInfo, None], None, None]:
    """Generate valid peers."""
    return (pr for pr in peers if pr.is_valid())
```
to this
```
def valid_peers(
    peers: typing.List[PeerInfo],
) -> list[PeerInfo]:
    """Generate valid peers."""
    return list((pr for pr in peers if pr.is_valid()))
```
solved my problem :)
